/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.moon_phase;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int moon0=0x7f020001;
        public static final int moon1=0x7f020002;
        public static final int moon10=0x7f020003;
        public static final int moon11=0x7f020004;
        public static final int moon12=0x7f020005;
        public static final int moon13=0x7f020006;
        public static final int moon14=0x7f020007;
        public static final int moon15=0x7f020008;
        public static final int moon16=0x7f020009;
        public static final int moon17=0x7f02000a;
        public static final int moon18=0x7f02000b;
        public static final int moon19=0x7f02000c;
        public static final int moon2=0x7f02000d;
        public static final int moon20=0x7f02000e;
        public static final int moon21=0x7f02000f;
        public static final int moon22=0x7f020010;
        public static final int moon23=0x7f020011;
        public static final int moon24=0x7f020012;
        public static final int moon25=0x7f020013;
        public static final int moon26=0x7f020014;
        public static final int moon27=0x7f020015;
        public static final int moon28=0x7f020016;
        public static final int moon29=0x7f020017;
        public static final int moon3=0x7f020018;
        public static final int moon4=0x7f020019;
        public static final int moon5=0x7f02001a;
        public static final int moon6=0x7f02001b;
        public static final int moon7=0x7f02001c;
        public static final int moon8=0x7f02001d;
        public static final int moon9=0x7f02001e;
    }
    public static final class id {
        public static final int slider_view=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int first_quarter=0x7f040003;
        public static final int full_moon=0x7f040004;
        public static final int hello=0x7f040000;
        public static final int new_moon=0x7f040002;
        public static final int third_quarter=0x7f040005;
        public static final int waning_crescent=0x7f040009;
        public static final int waning_gibbous=0x7f040008;
        public static final int waxing_crescent=0x7f040006;
        public static final int waxing_gibbous=0x7f040007;
    }
}
